[build]
  publish = ".next"
  command = "CI= npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://sei22-production.herokuapp.com"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://sei22-staging.herokuapp.com"
